// School database — used by the prober to auto-generate candidate RSS URLs
// Fields:
//   name:          full school name (used in Google News queries)
//   short:         short name for queries (e.g. "Alabama" not "University of Alabama")
//   conf:          conference
//   paperDomain:   college newspaper domain (prober tries RSS patterns against this)
//   herSlug:       Her Campus chapter slug (hercampus.com/school/{herSlug}/feed/)
//   city:          city name (for local news Google News queries)
//   localDomain:   local news site domain to probe (optional)

export type School = {
  name: string
  short: string
  conf: string
  paperDomain?: string
  herSlug?: string
  city?: string
  localDomain?: string
}

export const SCHOOLS: School[] = [

  // ── SEC ───────────────────────────────────────────────────────────────────
  { name: 'University of Alabama', short: 'Alabama', conf: 'SEC',
    paperDomain: 'thecrimsonwhite.com', herSlug: 'ua', city: 'Tuscaloosa', localDomain: 'tuscaloosathread.com' },
  { name: 'Auburn University', short: 'Auburn', conf: 'SEC',
    paperDomain: 'theplainsman.com', herSlug: 'auburn', city: 'Auburn' },
  { name: 'University of Florida', short: 'Florida', conf: 'SEC',
    paperDomain: 'alligator.org', herSlug: 'ufl', city: 'Gainesville', localDomain: 'gainesvillesun.com' },
  { name: 'University of Georgia', short: 'Georgia', conf: 'SEC',
    paperDomain: 'redandblack.com', herSlug: 'georgia', city: 'Athens', localDomain: 'onlineathens.com' },
  { name: 'University of Kentucky', short: 'Kentucky', conf: 'SEC',
    paperDomain: 'kykernel.com', herSlug: 'kentucky', city: 'Lexington' },
  { name: 'Louisiana State University', short: 'LSU', conf: 'SEC',
    paperDomain: 'lsureveille.com', herSlug: 'lsu', city: 'Baton Rouge', localDomain: 'nola.com' },
  { name: 'Mississippi State University', short: 'Mississippi State', conf: 'SEC',
    paperDomain: 'reflector-online.com', herSlug: 'mississippi-state', city: 'Starkville' },
  { name: 'University of Missouri', short: 'Missouri', conf: 'SEC',
    paperDomain: 'themaneater.com', herSlug: 'missouri', city: 'Columbia' },
  { name: 'University of Mississippi', short: 'Ole Miss', conf: 'SEC',
    paperDomain: 'thedmonline.com', herSlug: 'ole-miss', city: 'Oxford', localDomain: 'oxfordeagle.com' },
  { name: 'University of South Carolina', short: 'South Carolina', conf: 'SEC',
    paperDomain: 'dailygamecock.com', herSlug: 'south-carolina', city: 'Columbia' },
  { name: 'University of Tennessee', short: 'Tennessee', conf: 'SEC',
    paperDomain: 'utdailybeacon.com', herSlug: 'tennessee', city: 'Knoxville' },
  { name: 'Texas A&M University', short: 'Texas A&M', conf: 'SEC',
    paperDomain: 'thebatt.com', herSlug: 'texas-am', city: 'College Station' },
  { name: 'University of Texas', short: 'Texas', conf: 'SEC',
    paperDomain: 'thedailytexan.com', herSlug: 'texas', city: 'Austin' },
  { name: 'Vanderbilt University', short: 'Vanderbilt', conf: 'SEC',
    paperDomain: 'vanderbilthustler.com', herSlug: 'vanderbilt', city: 'Nashville' },
  { name: 'University of Arkansas', short: 'Arkansas', conf: 'SEC',
    paperDomain: 'uatrav.com', herSlug: 'u-of-arkansas', city: 'Fayetteville' },
  { name: 'University of Oklahoma', short: 'Oklahoma', conf: 'SEC',
    paperDomain: 'oudaily.com', herSlug: 'ou', city: 'Norman' },
  { name: 'Oklahoma State University', short: 'Oklahoma State', conf: 'SEC',
    paperDomain: 'ocolly.com', herSlug: 'oklahoma-state', city: 'Stillwater' },

  // ── BIG TEN ───────────────────────────────────────────────────────────────
  { name: 'University of Michigan', short: 'Michigan', conf: 'Big Ten',
    paperDomain: 'michigandaily.com', herSlug: 'u-michigan', city: 'Ann Arbor', localDomain: 'mlive.com' },
  { name: 'Ohio State University', short: 'Ohio State', conf: 'Big Ten',
    paperDomain: 'thelantern.com', herSlug: 'ohio-state', city: 'Columbus' },
  { name: 'University of Illinois', short: 'Illinois', conf: 'Big Ten',
    paperDomain: 'dailyillini.com', herSlug: 'illinois', city: 'Champaign' },
  { name: 'Indiana University', short: 'Indiana', conf: 'Big Ten',
    paperDomain: 'idsnews.com', herSlug: 'indiana', city: 'Bloomington' },
  { name: 'University of Iowa', short: 'Iowa', conf: 'Big Ten',
    paperDomain: 'dailyiowan.com', herSlug: 'u-iowa', city: 'Iowa City' },
  { name: 'University of Maryland', short: 'Maryland', conf: 'Big Ten',
    paperDomain: 'dbknews.com', herSlug: 'umd', city: 'College Park' },
  { name: 'Michigan State University', short: 'Michigan State', conf: 'Big Ten',
    paperDomain: 'statenews.com', herSlug: 'msu', city: 'East Lansing' },
  { name: 'University of Minnesota', short: 'Minnesota', conf: 'Big Ten',
    paperDomain: 'mndaily.com', herSlug: 'minnesota', city: 'Minneapolis' },
  { name: 'Northwestern University', short: 'Northwestern', conf: 'Big Ten',
    paperDomain: 'dailynorthwestern.com', herSlug: 'northwestern', city: 'Evanston' },
  { name: 'Penn State University', short: 'Penn State', conf: 'Big Ten',
    paperDomain: 'psucollegian.com', herSlug: 'penn-state', city: 'State College' },
  { name: 'Purdue University', short: 'Purdue', conf: 'Big Ten',
    paperDomain: 'purdueexponent.org', herSlug: 'purdue', city: 'West Lafayette' },
  { name: 'Rutgers University', short: 'Rutgers', conf: 'Big Ten',
    paperDomain: 'dailytargum.com', herSlug: 'rutgers', city: 'New Brunswick' },
  { name: 'University of Wisconsin', short: 'Wisconsin', conf: 'Big Ten',
    paperDomain: 'badgerherald.com', herSlug: 'wisconsin', city: 'Madison' },
  { name: 'University of Nebraska', short: 'Nebraska', conf: 'Big Ten',
    paperDomain: 'dailynebraskan.com', herSlug: 'nebraska', city: 'Lincoln' },
  { name: 'University of Washington', short: 'Washington', conf: 'Big Ten',
    paperDomain: 'dailyuw.com', herSlug: 'washington', city: 'Seattle' },
  { name: 'University of Oregon', short: 'Oregon', conf: 'Big Ten',
    paperDomain: 'dailyemerald.com', herSlug: 'uoregon', city: 'Eugene' },
  { name: 'UCLA', short: 'UCLA', conf: 'Big Ten',
    paperDomain: 'dailybruin.com', herSlug: 'ucla', city: 'Los Angeles' },
  { name: 'USC', short: 'USC', conf: 'Big Ten',
    paperDomain: 'dailytrojan.com', herSlug: 'usc', city: 'Los Angeles' },

  // ── BIG 12 ────────────────────────────────────────────────────────────────
  { name: 'Texas Tech University', short: 'Texas Tech', conf: 'Big 12',
    paperDomain: 'dailytoreador.com', herSlug: 'texas-tech', city: 'Lubbock' },
  { name: 'TCU', short: 'TCU', conf: 'Big 12',
    paperDomain: 'tcu360.com', herSlug: 'tcu', city: 'Fort Worth' },
  { name: 'Baylor University', short: 'Baylor', conf: 'Big 12',
    paperDomain: 'baylorlariat.com', herSlug: 'baylor', city: 'Waco' },
  { name: 'Kansas State University', short: 'Kansas State', conf: 'Big 12',
    paperDomain: 'kstatecollegian.com', herSlug: 'k-state', city: 'Manhattan' },
  { name: 'University of Kansas', short: 'Kansas', conf: 'Big 12',
    paperDomain: 'kansan.com', herSlug: 'university-of-kansas', city: 'Lawrence' },
  { name: 'Iowa State University', short: 'Iowa State', conf: 'Big 12',
    paperDomain: 'iowastatedaily.com', herSlug: 'iowa-state', city: 'Ames' },
  { name: 'West Virginia University', short: 'West Virginia', conf: 'Big 12',
    paperDomain: 'thedaonline.com', herSlug: 'west-virginia', city: 'Morgantown' },
  { name: 'University of Colorado', short: 'Colorado', conf: 'Big 12',
    paperDomain: 'coloradodaily.com', herSlug: 'cu-boulder', city: 'Boulder' },
  { name: 'Arizona State University', short: 'Arizona State', conf: 'Big 12',
    paperDomain: 'statepress.com', herSlug: 'asu', city: 'Tempe' },
  { name: 'University of Arizona', short: 'Arizona', conf: 'Big 12',
    paperDomain: 'wildcat.arizona.edu', herSlug: 'arizona', city: 'Tucson' },
  { name: 'University of Cincinnati', short: 'Cincinnati', conf: 'Big 12',
    paperDomain: 'newsrecord.org', herSlug: 'uc', city: 'Cincinnati' },
  { name: 'University of Houston', short: 'Houston', conf: 'Big 12',
    paperDomain: 'thedailycougar.com', herSlug: 'uh', city: 'Houston' },
  { name: 'University of Utah', short: 'Utah', conf: 'Big 12',
    paperDomain: 'dailyutahchronicle.com', herSlug: 'utah', city: 'Salt Lake City' },
  { name: 'UCF', short: 'UCF', conf: 'Big 12',
    paperDomain: 'centralfloridafuture.com', herSlug: 'ucf', city: 'Orlando' },
  { name: 'BYU', short: 'BYU', conf: 'Big 12',
    paperDomain: 'universe.byu.edu', city: 'Provo' },

  // ── ACC ───────────────────────────────────────────────────────────────────
  { name: 'Duke University', short: 'Duke', conf: 'ACC',
    paperDomain: 'dukechronicle.com', herSlug: 'duke', city: 'Durham' },
  { name: 'University of North Carolina', short: 'UNC', conf: 'ACC',
    paperDomain: 'dailytarheel.com', herSlug: 'unc', city: 'Chapel Hill' },
  { name: 'NC State University', short: 'NC State', conf: 'ACC',
    paperDomain: 'technicianonline.com', herSlug: 'nc-state', city: 'Raleigh' },
  { name: 'University of Virginia', short: 'Virginia', conf: 'ACC',
    paperDomain: 'cavalierdaily.com', herSlug: 'uva', city: 'Charlottesville' },
  { name: 'Virginia Tech', short: 'Virginia Tech', conf: 'ACC',
    paperDomain: 'collegiatetimes.com', herSlug: 'virginia-tech', city: 'Blacksburg' },
  { name: 'University of Miami', short: 'Miami', conf: 'ACC',
    paperDomain: 'themiamihurricane.com', herSlug: 'u-miami', city: 'Coral Gables' },
  { name: 'Florida State University', short: 'Florida State', conf: 'ACC',
    paperDomain: 'fsunews.com', herSlug: 'fsu', city: 'Tallahassee' },
  { name: 'University of Pittsburgh', short: 'Pitt', conf: 'ACC',
    paperDomain: 'pittnews.com', herSlug: 'pitt', city: 'Pittsburgh' },
  { name: 'Syracuse University', short: 'Syracuse', conf: 'ACC',
    paperDomain: 'dailyorange.com', herSlug: 'syracuse', city: 'Syracuse' },
  { name: 'Boston College', short: 'Boston College', conf: 'ACC',
    paperDomain: 'bcheights.com', herSlug: 'bc', city: 'Chestnut Hill' },
  { name: 'Georgia Tech', short: 'Georgia Tech', conf: 'ACC',
    paperDomain: 'nique.net', herSlug: 'georgia-tech', city: 'Atlanta' },
  { name: 'University of Notre Dame', short: 'Notre Dame', conf: 'ACC',
    paperDomain: 'ndsmcobserver.com', herSlug: 'notre-dame', city: 'South Bend' },
  { name: 'Clemson University', short: 'Clemson', conf: 'ACC',
    paperDomain: 'thetigercu.com', herSlug: 'clemson', city: 'Clemson' },
  { name: 'Wake Forest University', short: 'Wake Forest', conf: 'ACC',
    paperDomain: 'ogbonline.com', herSlug: 'wake-forest', city: 'Winston-Salem' },
  { name: 'Stanford University', short: 'Stanford', conf: 'ACC',
    paperDomain: 'stanforddaily.com', herSlug: 'stanford', city: 'Palo Alto' },
  { name: 'UC Berkeley', short: 'Cal', conf: 'ACC',
    paperDomain: 'dailycal.org', herSlug: 'uc-berkeley', city: 'Berkeley' },
  { name: 'SMU', short: 'SMU', conf: 'ACC',
    paperDomain: 'smudailymustang.com', herSlug: 'smu', city: 'Dallas' },
  { name: 'University of Louisville', short: 'Louisville', conf: 'ACC',
    paperDomain: 'thecardinalnews.com', herSlug: 'u-of-l', city: 'Louisville' },
  { name: 'University of California, Santa Barbara', short: 'UCSB', conf: 'ACC' },
  { name: 'Cal Poly San Luis Obispo', short: 'Cal Poly', conf: 'Ind' },

  // ── NOTABLE GREEK SCHOOLS (Independent / Other) ───────────────────────────
  { name: 'Tulane University', short: 'Tulane', conf: 'AAC',
    paperDomain: 'tulanehullabaloo.com', herSlug: 'tulane', city: 'New Orleans', localDomain: 'nola.com' },
  { name: 'Georgetown University', short: 'Georgetown', conf: 'Big East',
    paperDomain: 'thehoya.com', herSlug: 'georgetown', city: 'Washington DC' },
  { name: 'New York University', short: 'NYU', conf: 'Ind',
    paperDomain: 'nyunews.com', herSlug: 'nyu', city: 'New York' },
  { name: 'Dartmouth College', short: 'Dartmouth', conf: 'Ivy',
    paperDomain: 'thedartmouth.com', herSlug: 'dartmouth', city: 'Hanover' },
  { name: 'Cornell University', short: 'Cornell', conf: 'Ivy',
    paperDomain: 'cornellsun.com', herSlug: 'cornell', city: 'Ithaca' },
  { name: 'University of Pennsylvania', short: 'Penn', conf: 'Ivy',
    paperDomain: 'thedp.com', herSlug: 'upenn', city: 'Philadelphia' },
  { name: 'Lehigh University', short: 'Lehigh', conf: 'Patriot',
    paperDomain: 'thebrownandwhite.com', herSlug: 'lehigh', city: 'Bethlehem' },
  { name: 'Bucknell University', short: 'Bucknell', conf: 'Patriot',
    paperDomain: 'thebucknellian.net', herSlug: 'bucknell', city: 'Lewisburg' },
  { name: 'James Madison University', short: 'JMU', conf: 'Sun Belt',
    paperDomain: 'breezejmu.org', herSlug: 'jmu', city: 'Harrisonburg' },
  { name: 'George Washington University', short: 'GWU', conf: 'A-10',
    paperDomain: 'gwhatchet.com', herSlug: 'gwu', city: 'Washington DC' },
  { name: 'University of Denver', short: 'Denver', conf: 'Summit',
    paperDomain: 'duclarion.com', herSlug: 'du', city: 'Denver' },
  { name: 'Ohio University', short: 'Ohio', conf: 'MAC',
    paperDomain: 'thepostathens.com', herSlug: 'ohio-university', city: 'Athens' },
  { name: 'Western Kentucky University', short: 'Western Kentucky', conf: 'CUSA',
    paperDomain: 'wkuherald.com', herSlug: 'wku', city: 'Bowling Green' },
  { name: 'University of Mississippi Medical', short: 'Ole Miss Med', conf: 'SEC' },
  { name: 'Elon University', short: 'Elon', conf: 'CAA',
    paperDomain: 'elonpendulum.com', herSlug: 'elon', city: 'Elon' },
  { name: 'Pepperdine University', short: 'Pepperdine', conf: 'WCC',
    paperDomain: 'pepperdine-graphic.com', herSlug: 'pepperdine', city: 'Malibu' },
  { name: 'University of San Diego', short: 'San Diego', conf: 'WCC',
    paperDomain: 'theusdvista.com', city: 'San Diego' },
  { name: 'Villanova University', short: 'Villanova', conf: 'Big East',
    paperDomain: 'villanovan.com', herSlug: 'villanova', city: 'Villanova' },
  { name: 'DePaul University', short: 'DePaul', conf: 'Big East',
    herSlug: 'depaul', city: 'Chicago' },
  { name: 'University of Denver', short: 'Denver', conf: 'Ind' },
  { name: 'Rollins College', short: 'Rollins', conf: 'SSC',
    city: 'Winter Park' },
  { name: 'University of Alabama at Birmingham', short: 'UAB', conf: 'CUSA',
    city: 'Birmingham' },
  { name: 'University of Mississippi Southern', short: 'Southern Miss', conf: 'Sun Belt',
    city: 'Hattiesburg' },
  { name: 'Louisiana Tech University', short: 'Louisiana Tech', conf: 'CUSA',
    city: 'Ruston' },
  { name: 'University of Georgia Athens', short: 'UGA', conf: 'SEC' },

  // ── HBCU / NPHC ───────────────────────────────────────────────────────────
  { name: 'Howard University', short: 'Howard', conf: 'MEAC',
    paperDomain: 'thehilltoponline.com', herSlug: 'howard', city: 'Washington DC' },
  { name: 'Spelman College', short: 'Spelman', conf: 'SIAC',
    herSlug: 'spelman', city: 'Atlanta' },
  { name: 'Hampton University', short: 'Hampton', conf: 'MEAC',
    city: 'Hampton' },
  { name: 'Florida A&M University', short: 'FAMU', conf: 'MEAC',
    paperDomain: 'famuan.com', city: 'Tallahassee' },
  { name: 'Morgan State University', short: 'Morgan State', conf: 'MEAC',
    city: 'Baltimore' },
  { name: 'Grambling State University', short: 'Grambling', conf: 'SWAC',
    city: 'Grambling' },
]
